### ISSUE TITLE
Development environment Testing

### ISSUE THREAD

**Issue by harinarayanann** [Epinova/Addon.Episerver.EnvironmentSynchronizer#10]
Hi,
We are trying to use these solutions, currently, we are trying to test in the Development environment, below are the steps followed.
1. Installed the nugget into the local development environment.
2. Added the required configurations in the web.config
3. Restored the DB copy from PREP to the local DEV server.
4. Run the application.

With the above steps, If my understanding is right. the Synchronizer should copy the SiteDefinitions from web.config to CMS DB and I should be able to see the site.

**But it's not copying the Site Definitions.**, 

Also, One more issue here, the Addon is not adding to the Project reference automatically after installing the nugget. when we try to add manually its gives an error while running the application.

Can please help us to resolve the above issues.

Regards,
Hari

**Comment by LinusEkstrom** [comment]
Hi @harinarayanann,

I just tried installing the Nuget-package to an Optimizely .Net Framework project, and it installs and adds a reference as expected. Could you give a bit more information on what you are doing and what versions you are trying? Can you try and install the dependency to a local Alloy site or similar to see if that works?

Regards
Linus
