### ISSUE TITLE
Environment Synchronization Job with guid 1eda8c91-a367-41df-adee-e6143b1e37c3 is not registered first time after deploy

### ISSUE THREAD

**Issue by oyvindwh** [Epinova/Addon.Episerver.EnvironmentSynchronizer#20]
Great module!

When I install the module and add settings to appsettings.json in the same deploy the module fails since it can not find the Environment Synchronization job with guid 1eda8c91-a367-41df-adee-e6143b1e37c3 is not registered.

This code throws an error:

` this._scheduledJobExecutor.StartAsync(this._scheduledJobRepository.Get(Guid.Parse(((ScheduledPlugInAttribute) typeof (EnvironmentSynchronizationJob).GetCustomAttributes(typeof (ScheduledPlugInAttribute), true)[0]).GUID)), new JobExecutionOptions()
`

with message: "Could not get find or load EnvironmentSynchronizationJob. SynchronizationInitializationModule will not run."

It's an easy workaround, first deploy the nuget package and then add the settings in appsettings.json. Or just run the job in Settings in Optimizely the first time.

If this is a known behavior for all installations of the module perhaps update the readme file in the project so developers know before they have to debug and find out?

**Comment by LinusEkstrom** [comment]
@ovelartelius Have you heard/seen any issues with this before?

**Comment by oyvindwh** [comment]
This is the error from Application Insight:

```
Could not get find or load EnvironmentSynchronizationJob. SynchronizationInitializationModule will not run.
System.ArgumentNullException: Value cannot be null. (Parameter 'job')
   at EPiServer.Scheduler.Internal.DefaultScheduledJobExecutor.StartAsync(ScheduledJob job, JobExecutionOptions options, CancellationToken cancellationToken)
   at EPiServer.Scheduler.ScheduledJobExecutorExtensions.StartAsync(IScheduledJobExecutor executor, ScheduledJob job, JobExecutionOptions options)
   at Addon.Episerver.EnvironmentSynchronizer.InitializationModule.InitializationExecuter.Initialize() in /home/vsts/work/1/s/Addon.Episerver.EnvironmentSynchronizer/InitializationModule/InitializationExecuter.cs:line 71 

```
The nuget package must be installed in the environment you are copying the environment from (of course).

**Comment by LinusEkstrom** [comment]
Thanks for the stack trace @oyvindwh . Seems like a easy enough fix, let's see if we can get it out soon...

**Comment by LinusEkstrom** [comment]
@oyvindwh FYI - summer came between, but we'll start looking at this now.

**Comment by LinusEkstrom** [comment]
@oyvindwh Apparantly this was fixed during this summer and should be part of the latest release. Please test and confirm that your issue was solved.
