### ISSUE TITLE
Search reindex job fails when environment synchronizer is triggered automatically

### ISSUE THREAD

**Issue by ConorHarringtonSR** [Epinova/Addon.Episerver.EnvironmentSynchronizer#22]
I have configured the environment synchronizer job to trigger the search reindex job after a database sync (e.g. prod => preprod). But the search reindex job fails (as shown in the image) when the environment synchronizer is triggered automatically. However, when I manually run the environment sync job everything works correctly.

![image](https://github.com/user-attachments/assets/a50ef57a-4408-466f-9acc-56f9ded9c587)

![image](https://github.com/user-attachments/assets/1a6613aa-b341-47f2-99b6-ff410d5d1633)

**Comment by LinusEkstrom** [comment]
Hi @conorhepi . Could you possible share the stack trace of the error that you are getting from the logs?

**Comment by ConorHarringtonSR** [comment]
Here's the stack trace:
![image](https://github.com/user-attachments/assets/c28b14f4-25f3-402d-9512-0582ce6d878a)

**Comment by ovelartelius** [comment]
https://marisks.net/2019/04/23/episerver-starting-scheduled-job-programmatically/ 
Could be a solution...

**Comment by ovelartelius** [comment]
Solved by using custom handler. Search and navigation reindex job using HttpContext and is not available when run autorun. Read more: https://github.com/Epinova/Addon.Episerver.EnvironmentSynchronizer/blob/main/documentation/SearchReindexSynchronizer.md
